### ISSUE TITLE
odooup init fails on linux mint 19.2

### ISSUE THREAD

**Issue by yucer** [xoe-labs/dockery-odoo#15]
**Failing command:**

```
$ odooup init ocatest3
Please select Odoo version: 
 Available: 10.0, 11.0, 12.0, master
 Select: (10, 11, 12, m): 12
Use Odoo Enterprise (access required) [y/N]: 
Add additional repo [y/N]: 
```

**Error**:

```
An unexpected error has occurred: CalledProcessError: Command: ('/usr/bin/python', '-mvirtualenv', '/home/yucer/.cache/pre-commit/repo882hVB/py_env-python3.7', '-p', 'python3.7')
Return code: 3
Expected return code: 0
Output: 
    The path python3.7 (from --python=python3.7) does not exist
    
Errors: (none)

Traceback (most recent call last):
  File "/home/yucer/.local/lib/python2.7/site-packages/pre_commit/error_handler.py", line 46, in error_handler
    yield
  File "/home/yucer/.local/lib/python2.7/site-packages/pre_commit/main.py", line 304, in main
    skip_on_missing_config=args.allow_missing_config,
  File "/home/yucer/.local/lib/python2.7/site-packages/pre_commit/commands/install_uninstall.py", line 125, in install
    install_hooks(config_file, store)
  File "/home/yucer/.local/lib/python2.7/site-packages/pre_commit/commands/install_uninstall.py", line 131, in install_hooks
    install_hook_envs(all_hooks(load_config(config_file), store), store)
  File "/home/yucer/.local/lib/python2.7/site-packages/pre_commit/repository.py", line 215, in install_hook_envs
    hook.install()
  File "/home/yucer/.local/lib/python2.7/site-packages/pre_commit/repository.py", line 93, in install
    self.prefix, self.language_version, self.additional_dependencies,
  File "/home/yucer/.local/lib/python2.7/site-packages/pre_commit/languages/python.py", line 161, in install_environment
    _make_venv(env_dir, python)
  File "/home/yucer/.local/lib/python2.7/site-packages/pre_commit/languages/python.py", line 173, in make_venv
    cmd_output(*cmd, env=env, cwd='/')
  File "/home/yucer/.local/lib/python2.7/site-packages/pre_commit/util.py", line 153, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
CalledProcessError: Command: ('/usr/bin/python', '-mvirtualenv', '/home/yucer/.cache/pre-commit/repo882hVB/py_env-python3.7', '-p', 'python3.7')
Return code: 3
Expected return code: 0
Output: 
    The path python3.7 (from --python=python3.7) does not exist
```

**System**

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19.2 Tina
Release:	19.2
Codename:	tina

$ python --version
Python 2.7.15+

$ python3 --version
Python 3.6.8
```

**Comment by blaggacao** [comment]
@yucer Did you manage to install python 3.7 ?

**Comment by yucer** [comment]
@blaggacao Sorry for the late response.

Yes, it works in python3.7.

It is a very nice job, I will continue testing it later.

Thanks.
